Colocando log na camada de controller e service
marcos1228/microservice-order pull request #5
Opened 2022-02-04 18:35 UTC by marcos1228

Adicionando log na camada de controller e service...

2022-02-04 18:49 UTC, oliveira-edu requested changes

2022-02-04 18:49 UTC, oliveira-edu commented on src/main/java/com/order/config/ClientErrorDecoder.java
> +		e.getMessage();
o que está acontecendo com essa linha 35 e 36?

pq essas linhas estao aqui?

2022-02-04 18:49 UTC, oliveira-edu commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("The order return");
eu recomendaria utilizar o padrão:
method=getByOrder message="buscando order por id" orderId=" + id"

assim, ao utlizaar o splunk poderiamos busca por metodo,  por id ou por mensagem.

2022-02-04 18:49 UTC, oliveira-edu commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("Orders will be listed in pageable form");
eu recomendaria utilizar o padrão:
method=.....  message=....   q nem eu disse no outro comentario

2022-02-04 18:49 UTC, oliveira-edu commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("The order saved");
method=.... message=pedido cadastrado com sucesso

2022-02-04 18:49 UTC, oliveira-edu commented on src/main/java/com/order/domain/dto/response/OrderResponseDto.java
> +	private Long idLong;
pq tem dois ids aqui?

2022-02-04 18:49 UTC, oliveira-edu commented on src/test/java/com/order/service/OrderValidatorTest.java
> -//		verify(productClient).getByProduct("03");
os testes foram removidos?

2022-02-04 19:03 UTC, marcos1228 commented on src/main/java/com/order/config/ClientErrorDecoder.java
> +		e.getMessage();
Opa! Me equivoquei nessa duas linhas...
Acho que a forma correta seria assim: log.info("ERROR_DEFAULT_WITHOUT_HTTP_CODE", e.getCause(), e.getMessage());

2022-02-04 19:04 UTC, marcos1228 commented on src/main/java/com/order/domain/dto/response/OrderResponseDto.java
> +	private Long idLong;
Realmente, esses dois atritos estão duplicado....

2022-02-04 19:05 UTC, marcos1228 commented on src/test/java/com/order/service/OrderValidatorTest.java
> -//		verify(productClient).getByProduct("03");
Esses testes, foram removido pq, agora eu não tenho mais um idProduct só, mais sim uma lista de itens...

2022-02-04 19:09 UTC, marcos1228 commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("The order return");
Aqui eu fiquei meio confuso....
Exemplificando seria isso abaixo? 
log.info("method=getByOrder message=buscando order por id", id);

2022-02-04 19:19 UTC, oliveira-edu commented on src/main/java/com/order/config/ClientErrorDecoder.java
> +		e.getMessage();
e oque signficia essa linha 34? 
o q significa esse "ERROR_DEFAULT_WITHOUT_HTTP_CODE"?

2022-02-04 19:21 UTC, oliveira-edu commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("The order return");
ora, como funciona esse cara aqui?

log.info("method=getByOrder message=buscando order por id, orderId={} , id);

o slf4 vai pegar o id e colocar no lugar das chaves lá. pra vc n precisar colar strings

2022-02-04 19:21 UTC, oliveira-edu commented on src/test/java/com/order/service/OrderValidatorTest.java
> -//		verify(productClient).getByProduct("03");
entendi

2022-02-07 13:04 UTC, marcos1228 commented on src/main/java/com/order/config/ClientErrorDecoder.java
> +		e.getMessage();
Ele registra uma mensagem de info, levando em consideração ao formato especificado...
ERROR_DEFAULT_WITHOUT_HTTP_CODE -->> Seria a mensagem que ele retorna dentro do log, quando ele cair na exceção do Tray....

2022-02-08 12:07 UTC, marcos1228 commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("The order return");
Opa....Corrigido....

2022-02-08 12:07 UTC, marcos1228 commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("Orders will be listed in pageable form");
Opa....Corrigido.

2022-02-08 12:35 UTC, oliveira-edu commented on src/main/java/com/order/config/ClientErrorDecoder.java
> +		e.getMessage();
sim, mas o que significa "ERROR_DEFAULT_WITHOUT_HTTP_CODE " - o que isso ajuda quem esta lendo o log a entender o que aconteceu?

2022-02-09 12:23 UTC, oliveira-edu approved these changes

2022-02-09 12:23 UTC, oliveira-edu commented on src/main/java/com/order/controller/OrderController.java
> +		log.info("Method={} message={}", "save", "savando um pedido");
erro de tortografia aqui

2022-02-09 12:23 UTC, merged